#!/system/bin/sh
#Script originally made by Axetilen. Modified by Sultan (android1234567)
#Then updated for albinoman887's ChronicKernel (98% of the credit goes to android1234567. Thanks so much man :)
#Now updated again by Sultan (android1234567) for Sultan kernel

# Configure your options here #

# UKSM (Ultra KSM)
# It is recommended to enable this for better performance
# 0 = disabled
# 1 = enabled
UKSM=1

# Kernel Default: Ondemand
# Available options:
# Badass
# Ondemand
# Interactive
# Lagfee
# Performance
GOV=ondemand


# Config I/O scheduler
# Deadline (default)
# CFQ
# Noop
# BFQ
# V(R) 
# SIO
IO=deadline


# Config CPU max frequency
MAXFREQ=1512000


# Config CPU min frequency
# This should stay at 384MHz
MINFREQ=384000


# Config 3D GPU clock
# 228571000 = 228MHz
# 266667000 = 267MHz (default)
# 300000000 = 300MHz
# 320000000 = 320MHz
GPU=266667000


# Config 2D GPU clock
# 145455000 = 145MHz
# 160000000 = 160MHz
# 200000000 = 200MHz (default)
# 228571000 = 228MHz
# 266667000 = 267MHz
DD=200000000


# Badass Configuration
# 1 = performance
# 2 = balanced
# 3 = battery saving
BADASS=2


# Enable Sweep2Wake
# 0 = disabled (default)
# 1 = enabled
# 2 = enabled (with no button backlight during sweep)
SWEEP=0


# Enable Fastcharge
# 0 = disabled
# 1 = substitute AC to USB charging always
# 2 = substitute AC to USB charging only if there is no USB peripheral detected
FASTCHARGE=0


# Fsync Control
# 0 = Fsync disabled
# 1 = Fsync enabled
FSYNC=1


# End of configurable options #


################# DON'T CHANGE ANYTHING BELOW THIS LINE #################


## Config CPU governor
    echo "$GOV" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
    echo "$GOV" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor


# Config 3D GPU setting
    chmod 644 /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk
    chmod 644 /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/gpuclk
    echo $GPU > /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk
    echo $GPU > /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/gpuclk


# Config 2D GPU setting
    chmod 644 /sys/devices/platform/kgsl-2d0.0/kgsl/kgsl-2d0/max_gpuclk
    chmod 644 /sys/devices/platform/kgsl-2d0.0/kgsl/kgsl-2d0/gpuclk
    chmod 644 /sys/devices/platform/kgsl-2d1.1/kgsl/kgsl-2d1/max_gpuclk
    chmod 644 /sys/devices/platform/kgsl-2d1.1/kgsl/kgsl-2d1/gpuclk
    echo $DD > /sys/devices/platform/kgsl-2d0.0/kgsl/kgsl-2d0/max_gpuclk
    echo $DD > /sys/devices/platform/kgsl-2d0.0/kgsl/kgsl-2d0/gpuclk
    echo $DD > /sys/devices/platform/kgsl-2d1.1/kgsl/kgsl-2d1/max_gpuclk
    echo $DD > /sys/devices/platform/kgsl-2d1.1/kgsl/kgsl-2d1/gpuclk
 

# Config USB forced fastcharge
    chmod 644 /sys/kernel/fast_charge/force_fast_charge
    echo "$FASTCHARGE" > /sys/kernel/fast_charge/force_fast_charge


# Config Sweep2Wake (with compatibility with NLJ's fix)
	if [ "$SWEEP" = "0" ]
	then
                chown radio.system /sys/android_touch/sweep2wake
                chmod 664 /sys/android_touch/sweep2wake
   		echo 0 > /sys/android_touch/sweep2wake
	fi

	if [ "$SWEEP" = "1" ]
	then
    		chown radio.system /sys/android_touch/sweep2wake
                chmod 664 /sys/android_touch/sweep2wake
   		echo 1 > /sys/android_touch/sweep2wake
	fi

	if [ "$SWEEP" = "2" ]
	then
    		chown radio.system /sys/android_touch/sweep2wake
                chmod 664 /sys/android_touch/sweep2wake
   		echo 2 > /sys/android_touch/sweep2wake
	fi


# Config badass CPU Gonvernor
CUR_GOV="`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`"
echo badass > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
sleep 3
case ${BADASS} in
	1)
		$L "badass: setting performance-oriented configuration"
		echo 1188000 > /sys/devices/system/cpu/cpufreq/badass/two_phase_freq;
		echo 1512000 > /sys/devices/system/cpu/cpufreq/badass/three_phase_freq;
		echo 120 > /sys/devices/system/cpu/cpufreq/badass/busy_threshold;
		echo 80 > /sys/devices/system/cpu/cpufreq/badass/busy_clr_threshold;
		echo 8 > /sys/devices/system/cpu/cpufreq/badass/semi_busy_threshold;
		echo 4 > /sys/devices/system/cpu/cpufreq/badass/semi_busy_clr_threshold;
	;;
	2)
		$L "badass: setting balanced configuration"
		echo 918000 > /sys/devices/system/cpu/cpufreq/badass/two_phase_freq;
		echo 1188000 > /sys/devices/system/cpu/cpufreq/badass/three_phase_freq;
                echo 50000 > /sys/devices/system/cpu/cpufreq/badass/sampling_rate
		echo 130 > /sys/devices/system/cpu/cpufreq/badass/busy_threshold;
		echo 100 > /sys/devices/system/cpu/cpufreq/badass/busy_clr_threshold;
		echo 14 > /sys/devices/system/cpu/cpufreq/badass/semi_busy_threshold;
		echo 6 > /sys/devices/system/cpu/cpufreq/badass/semi_busy_clr_threshold;
	;;
	3)
		$L "badass: setting battery saving configuration"
		echo 918000 > /sys/devices/system/cpu/cpufreq/badass/two_phase_freq;
		echo 1188000 > /sys/devices/system/cpu/cpufreq/badass/three_phase_freq;
		echo 140 > /sys/devices/system/cpu/cpufreq/badass/busy_threshold;
		echo 110 > /sys/devices/system/cpu/cpufreq/badass/busy_clr_threshold;
		echo 80 > /sys/devices/system/cpu/cpufreq/badass/semi_busy_threshold;
		echo 20 > /sys/devices/system/cpu/cpufreq/badass/semi_busy_clr_threshold;
	;;
esac
echo ${CUR_GOV} > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor


# Config CPU Frequency
    chmod 644 /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
    echo "$MAXFREQ" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
    chmod 644 /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
    echo "$MINFREQ" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
 
    chmod 644 /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
    echo "$MAXFREQ" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
    chmod 644 /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
    echo "$MINFREQ" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq


# Config I/O scheduler
    chmod 644 /sys/block/mmcblk0/queue/scheduler
    echo "$IO" > /sys/block/mmcblk0/queue/scheduler
    chmod 644 /sys/block/mmcblk1/queue/scheduler
    echo "$IO" > /sys/block/mmcblk1/queue/scheduler


# Config Fsync
    echo "$FSYNC" > /sys/class/misc/fsynccontrol/fsync_enabled

# Config UKSM
echo "$UKSM" > /sys/kernel/mm/uksm/run
