#!/system/bin/sh

#### Change your own settings here ###
 
## Sweep2Wake
# 0 = Disabled
# 1 = Enabled
# 2 = Enabled (with no button backlight)
SWEEP=0;

## Display undervolt
# Choose a value between
# 0mV and 700mV that is a
# multiple of 25.
# Undervolt will be
# 3100mV -MINUS- (what you choose)
PANEL_UV=250;

## 3D GPU max frequency
# 177778000 = 177MHz
# 200000000 = 200MHz
# 228571000 = 228MHz
# 266667000 = 267MHz
# 300000000 = 300MHz
# 320000000 = 320MHz
GPU=266667000;

## CPU max frequency
MAXFREQ=1512000;

## CPU max frequency for EACH core
MAX0=;
MAX1=;

## CPU governor
# Ondemand
# Lagfree
# Performance
# Interactive
GOV=ondemand;

## MPdecision
# 1 = Enabled
# 0 = MPdecision disabled and both CPU cores forced online
MSM=1;

## Capacitive-button backlight brightness
# 1 = Backlight disabled
# 2 = Dimmer
# 3 = Normal
BACK=3;

####### DO NOT CHANGE ANYTHING BELOW THIS LINE #######

# Config Sweep2Wake
chmod 664 /sys/android_touch/sweep2wake
echo "$SWEEP" > /sys/android_touch/sweep2wake

# Config CPU governor
chmod 664 /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
chmod 664 /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
echo "$GOV" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo "$GOV" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
chmod 444 /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
chmod 444 /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor

# Config Display UV
echo "$PANEL_UV" > /sys/module/msm_mipi/parameters/panel_uv

# Config CPU Frequency
chmod 664 /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
chmod 664 /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
echo $MAXFREQ > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo $MAXFREQ > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
echo $MAX0 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo $MAX1 > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq

# Config 3D GPU setting
chmod 664 /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk
echo $GPU > /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk

# Config MPdecision
if [ "$MSM" = "1" ]
then
	chmod 664 /sys/module/autosmp/parameters/enabled
	echo "Y" > /sys/module/autosmp/parameters/enabled
	chmod 444 /sys/module/autosmp/parameters/enabled
	chmod 664 /sys/devices/system/cpu/cpu1/online
fi

if [ "$MSM" = "0" ]
then
	chmod 664 /sys/module/autosmp/parameters/enabled
	echo "0" > /sys/module/autosmp/parameters/enabled
	chmod 444 /sys/module/autosmp/parameters/enabled
	chmod 664 /sys/devices/system/cpu/cpu1/online
	echo "1" > /sys/devices/system/cpu/cpu1/online
	chmod 444 /sys/devices/system/cpu/cpu1/online
fi

# Capacitive buttons backlight
chown root:root /sys/devices/platform/leds-pm8058/leds/button-backlight/currents

if [ "$BACK" = "1" ]
then
	chmod 777 /sys/devices/platform/leds-pm8058/leds/button-backlight/currents
	echo "0" > /sys/devices/platform/leds-pm8058/leds/button-backlight/currents
	chmod 444 /sys/devices/platform/leds-pm8058/leds/button-backlight/currents
fi

if [ "$BACK" = "2" ]
then
	chmod 777 /sys/devices/platform/leds-pm8058/leds/button-backlight/currents
	echo "4" > /sys/devices/platform/leds-pm8058/leds/button-backlight/currents
	chmod 444 /sys/devices/platform/leds-pm8058/leds/button-backlight/currents
fi

if [ "$BACK" = "3" ]
then
	chmod 777 /sys/devices/platform/leds-pm8058/leds/button-backlight/currents
	echo "8" > /sys/devices/platform/leds-pm8058/leds/button-backlight/currents
	chmod 444 /sys/devices/platform/leds-pm8058/leds/button-backlight/currents
fi
