#!/system/bin/sh

### Change your own settings here ###

## Sweep2Wake
# 0 = Disabled
# 1 = Enabled
# 2 = Enabled (with no button backlight)
SWEEP=0;

## Display undervolt
# Choose a value between
# 0mV and 700mV that is a
# multiple of 25.
# Undervolt will be
# 3100mV -MINUS- (what you choose)
PANEL_UV=0;

## Display color control
# 0 = Regular colors
# 1 = Cooler colors
COLORS=0;

## Maximum GPU frequency
# 200000000 = 200MHz
# 228571000 = 228MHz
# 266667000 = 267MHz
# 300000000 = 300MHz
# 320000000 = 320MHz
GPU=266667000;

## Maximum CPU frequency
MAXFREQ=1512000;

## Capacitive-button backlight brightness
# 1 = Backlight disabled
# 2 = Dimmer
# 3 = Normal
BACK=3;

####### DO NOT CHANGE ANYTHING BELOW THIS LINE #######

# Sweep2Wake
chmod 664 /sys/android_touch/sweep2wake
echo "$SWEEP" > /sys/android_touch/sweep2wake

# Display undervolt
echo "$PANEL_UV" > /sys/module/board_pyramid_display/parameters/panel_uv

# Display colors
echo "$COLORS" > /sys/module/mdp/parameters/mdp_gamma_cooler_colors

# Maximum CPU frequency
chmod 664 /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo "$MAXFREQ" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq

# Maximum GPU frequency
chmod 664 /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk
echo "$GPU" > /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk

# Capacitive buttons backlight
chown root:root /sys/devices/platform/leds-pm8058/leds/button-backlight/currents

if [ "$BACK" = "1" ]
then
	chmod 777 /sys/devices/platform/leds-pm8058/leds/button-backlight/currents
	echo "0" > /sys/devices/platform/leds-pm8058/leds/button-backlight/currents
	chmod 444 /sys/devices/platform/leds-pm8058/leds/button-backlight/currents
fi

if [ "$BACK" = "2" ]
then
	chmod 777 /sys/devices/platform/leds-pm8058/leds/button-backlight/currents
	echo "4" > /sys/devices/platform/leds-pm8058/leds/button-backlight/currents
	chmod 444 /sys/devices/platform/leds-pm8058/leds/button-backlight/currents
fi

if [ "$BACK" = "3" ]
then
	chmod 777 /sys/devices/platform/leds-pm8058/leds/button-backlight/currents
	echo "10" > /sys/devices/platform/leds-pm8058/leds/button-backlight/currents
	chmod 444 /sys/devices/platform/leds-pm8058/leds/button-backlight/currents
fi
